velocity_modifier_node:
  ros__parameters:
    # 로봇이 움직이기 시작하는 최소 속도
    min_abs_linear_vel: 0.03
    min_abs_angular_vel: 0.03

    # 위 조건 만족 시, 비율 보정 후 적용될 최대 속도
    ratio_scaling_max_linear_vel: 0.3
    ratio_scaling_max_angular_vel: 0.2
