fleet_decision_node:
  ros__parameters:
    # --- Robot Identity ---
    my_machine_id: 1
    use_reroute: true

    # --- Wait Timeouts (Seconds) ---
    wait_detect_amr_sec: 2.0        # TYPE 1, 6, 7, 10, 12
    wait_other_amr_long_sec: 450.0  # TYPE 5 (Reroute ON)
    wait_other_amr_short_sec: 30.0  # TYPE 5 (Reroute OFF)
    wait_abnormal_long_sec: 300.0   # TYPE 2 (Reroute ON)
    wait_abnormal_short_sec: 30.0   # TYPE 2 (Reroute OFF)
    wait_obstacle_sec: 15.0         # TYPE 11 (General Obstacle)
    
    simple_mode: false  # [수정] Simple Mode 활성화 여부 (true/false)
    wait_simple_mode_sec: 5.0  # [수정] Simple Mode에서 대기하는 시간 (초)

    # --- Thresholds ---
    replan_ignore_sec_after_agent: 0.5
    collision_msg_timeout_sec: 3.0  # [수정] 충돌 메시지 타임아웃 설정
    reroute_cooldown_sec: 5.0       # [수정] Reroute 요청 쿨다운 시간 설정


    # --- Input Topics ---
    topic_collision: "/path_agent_collision_info"
    topic_agents: "/multi_agent_infos"
    # topic_replan_flag: "/replan_flag"
    topic_path_block_status: "/path_block_status"  # [NEW] 추가됨
    wall_hugging_wait_sec: 2.0  # [NEW] Wall hugging 감지 시 대기하는 시간 (초)
    direct_obs_clear_sec: 3.0   # [NEW] Direct Obstacle Clear 요구 시간 (초)
    direct_obs_timeout_sec: 15.0 # [NEW] Direct Obstacle 타임아웃 시간 (초)

    # --- Output Topics ---
    topic_decision_state: "/decision_state"
    topic_request_replan: "/request_replan"
    topic_request_reroute: "/request_reroute" # [NEW] 추가됨    
    topic_cmd_run: "/cmd/run"
    topic_cmd_resume: "/controller_pause_flag"   # <--- [NEW] 추가됨
    topic_cmd_stop: "/controller_pause_flag"

    replan_clear_timeout_sec: 2.0  # [NEW] Replan Flag가 False로 연속 유지되어야 하는 시간 (초)