<?xml version="1.0"?>
<package format="3">
  <name>replan_monitor</name>
  <version>0.1.0</version>
  <description>Global path replan monitor and Path Validator node for Nav2</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>multi_agent_msgs</build_depend>

  <!-- Build & run deps (format=3의 <depend>는 build+exec 겸용) -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <!-- <depend>nav2_common</depend> -->

  <!-- Launch/runtime helpers -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>multi_agent_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- pluginlib manifest가 생기면 여기에 추가 -->
  </export>
</package>




<!-- <?xml version="1.0"?>
<package format="3">
  <name>replan_monitor</name>
  <version>0.1.0</version>
  <description>Global path replan monitor based on local costmap analysis</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>nav2_common</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package> -->
